// <auto-generated />
using System;
using AquiEstoy.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AquiEstoy.Infrastructure.Migrations
{
    [DbContext(typeof(AquiEstoyDbContext))]
    partial class AquiEstoyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AquiEstoy.Domain.Entities.AdjuntoCaso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CasoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaSubida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SubidoPorId")
                        .HasColumnType("int");

                    b.Property<string>("TipoArchivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CasoId");

                    b.HasIndex("SubidoPorId");

                    b.ToTable("AdjuntosCaso", (string)null);
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Atendida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("AtendidaPorId")
                        .HasColumnType("int");

                    b.Property<int>("CasoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaAtencion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaGeneracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("TipoAlertaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtendidaPorId");

                    b.HasIndex("CasoId");

                    b.HasIndex("TipoAlertaId");

                    b.ToTable("Alertas", (string)null);
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DetalleJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EntidadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Auditoria", (string)null);
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Canton", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Cantones", (string)null);
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Caso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoCasoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaApertura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<int>("NivelSeveridadId")
                        .HasColumnType("int");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int?>("ProfesionalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoCasoId");

                    b.HasIndex("NivelSeveridadId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProfesionalId");

                    b.ToTable("Casos", (string)null);
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.CasoFactorRiesgo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CasoId")
                        .HasColumnType("int");

                    b.Property<int>("FactorRiesgoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CasoId");

                    b.HasIndex("FactorRiesgoId");

                    b.ToTable("CasoFactoresRiesgo", (string)null);
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.CategoriaFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasFactor", (string)null);
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Conversacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CasoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("ProfesionalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CasoId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProfesionalId");

                    b.ToTable("Conversaciones", (string)null);
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Especialidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Especialidades", (string)null);
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.EstadoCaso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("EstadosCaso", (string)null);
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.FactorRiesgo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PesoRiesgo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(1.00m);

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("FactoresRiesgo", (string)null);
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.HistorialSeveridad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CambiadoPorId")
                        .HasColumnType("int");

                    b.Property<int>("CasoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SeveridadAnterId")
                        .HasColumnType("int");

                    b.Property<int>("SeveridadNuevaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CambiadoPorId");

                    b.HasIndex("CasoId");

                    b.HasIndex("SeveridadAnterId");

                    b.HasIndex("SeveridadNuevaId");

                    b.ToTable("HistorialSeveridad", (string)null);
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.LineaAyuda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("LineasAyuda", (string)null);
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConversacionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("RemitenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConversacionId");

                    b.HasIndex("RemitenteId");

                    b.ToTable("Mensajes", (string)null);
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.NivelSeveridad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("NivelesSeveridad", (string)null);
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Profesional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("int");

                    b.Property<string>("NumColegiado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EspecialidadId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Profesionales", (string)null);
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Provincias", (string)null);
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.ReporteEstadistico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaGeneracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("GeneradoPorId")
                        .HasColumnType("int");

                    b.Property<string>("ParametrosFiltro")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ResultadoResumen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoReporte")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GeneradoPorId");

                    b.ToTable("ReportesEstadisticos", (string)null);
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.SesionChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaConexion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaDesconexion")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SesionesChat", (string)null);
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.TipoAlerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TiposAlerta", (string)null);
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CantonId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("ProvinciaId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CantonId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProvinciaId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.AdjuntoCaso", b =>
                {
                    b.HasOne("AquiEstoy.Domain.Entities.Caso", "Caso")
                        .WithMany("Adjuntos")
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AquiEstoy.Domain.Entities.Usuario", "SubidoPor")
                        .WithMany("AdjuntosSubidos")
                        .HasForeignKey("SubidoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caso");

                    b.Navigation("SubidoPor");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Alerta", b =>
                {
                    b.HasOne("AquiEstoy.Domain.Entities.Usuario", "AtendidaPor")
                        .WithMany("AlertasAtendidas")
                        .HasForeignKey("AtendidaPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AquiEstoy.Domain.Entities.Caso", "Caso")
                        .WithMany("Alertas")
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AquiEstoy.Domain.Entities.TipoAlerta", "TipoAlerta")
                        .WithMany("Alertas")
                        .HasForeignKey("TipoAlertaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AtendidaPor");

                    b.Navigation("Caso");

                    b.Navigation("TipoAlerta");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Auditoria", b =>
                {
                    b.HasOne("AquiEstoy.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RegistrosAuditoria")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Canton", b =>
                {
                    b.HasOne("AquiEstoy.Domain.Entities.Provincia", "Provincia")
                        .WithMany("Cantones")
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Caso", b =>
                {
                    b.HasOne("AquiEstoy.Domain.Entities.EstadoCaso", "EstadoCaso")
                        .WithMany("Casos")
                        .HasForeignKey("EstadoCasoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AquiEstoy.Domain.Entities.NivelSeveridad", "NivelSeveridad")
                        .WithMany("Casos")
                        .HasForeignKey("NivelSeveridadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AquiEstoy.Domain.Entities.Usuario", "Paciente")
                        .WithMany("CasosComoPaciente")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AquiEstoy.Domain.Entities.Profesional", "Profesional")
                        .WithMany("CasosAsignados")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EstadoCaso");

                    b.Navigation("NivelSeveridad");

                    b.Navigation("Paciente");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.CasoFactorRiesgo", b =>
                {
                    b.HasOne("AquiEstoy.Domain.Entities.Caso", "Caso")
                        .WithMany("FactoresRiesgo")
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AquiEstoy.Domain.Entities.FactorRiesgo", "FactorRiesgo")
                        .WithMany("Casos")
                        .HasForeignKey("FactorRiesgoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caso");

                    b.Navigation("FactorRiesgo");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Conversacion", b =>
                {
                    b.HasOne("AquiEstoy.Domain.Entities.Caso", "Caso")
                        .WithMany("Conversaciones")
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AquiEstoy.Domain.Entities.Usuario", "Paciente")
                        .WithMany("ConversacionesComoPaciente")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AquiEstoy.Domain.Entities.Profesional", "Profesional")
                        .WithMany("Conversaciones")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caso");

                    b.Navigation("Paciente");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.FactorRiesgo", b =>
                {
                    b.HasOne("AquiEstoy.Domain.Entities.CategoriaFactor", "Categoria")
                        .WithMany("FactoresRiesgo")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.HistorialSeveridad", b =>
                {
                    b.HasOne("AquiEstoy.Domain.Entities.Usuario", "CambiadoPor")
                        .WithMany("CambiosSeveridadRealizados")
                        .HasForeignKey("CambiadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AquiEstoy.Domain.Entities.Caso", "Caso")
                        .WithMany("HistorialSeveridad")
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AquiEstoy.Domain.Entities.NivelSeveridad", "SeveridadAnterior")
                        .WithMany("HistorialesComoAnterior")
                        .HasForeignKey("SeveridadAnterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AquiEstoy.Domain.Entities.NivelSeveridad", "SeveridadNueva")
                        .WithMany("HistorialesComoNuevo")
                        .HasForeignKey("SeveridadNuevaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CambiadoPor");

                    b.Navigation("Caso");

                    b.Navigation("SeveridadAnterior");

                    b.Navigation("SeveridadNueva");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Mensaje", b =>
                {
                    b.HasOne("AquiEstoy.Domain.Entities.Conversacion", "Conversacion")
                        .WithMany("Mensajes")
                        .HasForeignKey("ConversacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AquiEstoy.Domain.Entities.Usuario", "Remitente")
                        .WithMany("MensajesEnviados")
                        .HasForeignKey("RemitenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversacion");

                    b.Navigation("Remitente");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Profesional", b =>
                {
                    b.HasOne("AquiEstoy.Domain.Entities.Especialidad", "Especialidad")
                        .WithMany("Profesionales")
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AquiEstoy.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Profesional")
                        .HasForeignKey("AquiEstoy.Domain.Entities.Profesional", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.ReporteEstadistico", b =>
                {
                    b.HasOne("AquiEstoy.Domain.Entities.Usuario", "GeneradoPor")
                        .WithMany("ReportesGenerados")
                        .HasForeignKey("GeneradoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GeneradoPor");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.SesionChat", b =>
                {
                    b.HasOne("AquiEstoy.Domain.Entities.Usuario", "Usuario")
                        .WithMany("SesionesChat")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("AquiEstoy.Domain.Entities.Canton", "Canton")
                        .WithMany("Usuarios")
                        .HasForeignKey("CantonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AquiEstoy.Domain.Entities.Provincia", "Provincia")
                        .WithMany("Usuarios")
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AquiEstoy.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Canton");

                    b.Navigation("Provincia");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Canton", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Caso", b =>
                {
                    b.Navigation("Adjuntos");

                    b.Navigation("Alertas");

                    b.Navigation("Conversaciones");

                    b.Navigation("FactoresRiesgo");

                    b.Navigation("HistorialSeveridad");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.CategoriaFactor", b =>
                {
                    b.Navigation("FactoresRiesgo");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Conversacion", b =>
                {
                    b.Navigation("Mensajes");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Especialidad", b =>
                {
                    b.Navigation("Profesionales");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.EstadoCaso", b =>
                {
                    b.Navigation("Casos");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.FactorRiesgo", b =>
                {
                    b.Navigation("Casos");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.NivelSeveridad", b =>
                {
                    b.Navigation("Casos");

                    b.Navigation("HistorialesComoAnterior");

                    b.Navigation("HistorialesComoNuevo");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Profesional", b =>
                {
                    b.Navigation("CasosAsignados");

                    b.Navigation("Conversaciones");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Provincia", b =>
                {
                    b.Navigation("Cantones");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.TipoAlerta", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("AquiEstoy.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("AdjuntosSubidos");

                    b.Navigation("AlertasAtendidas");

                    b.Navigation("CambiosSeveridadRealizados");

                    b.Navigation("CasosComoPaciente");

                    b.Navigation("ConversacionesComoPaciente");

                    b.Navigation("MensajesEnviados");

                    b.Navigation("Profesional");

                    b.Navigation("RegistrosAuditoria");

                    b.Navigation("ReportesGenerados");

                    b.Navigation("SesionesChat");
                });
#pragma warning restore 612, 618
        }
    }
}
